# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dali`s Blogs # ex. I m Chuan
name: Ren Guangli  # ex. DONGChuan
email: renguangligg@gmail.com
location: Beijing # ex. Nice, France
company: Rgl
company_url: https://renguangli.com
github_url: https://github.com/renguangli # ex. https://github.com/DONGChuan
github_username: renguangli # ex. DONGChuan
description: dali`s Blogs, dali, 大力, 大力的博客
favicon: favicon.png # Image must be in assets/images
repository: renguangli/renguangli.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://renguangli.com
staticUrl: https://rgl-1252211075.cos.ap-beijing.myqcloud.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
permalink: /:title

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
# disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# https://github.com/gitalk/gitalk#install
gitalk:
  enable: true
  owner: renguangli
  repo: comments
  clientID: 8ff7ae9648607fe6e4b3
  clientSecret: 5ffe44de3ec03f5072ff5641e1d5aa58a9138c16

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 主页

    #  -
    #    href: /open-source
#    label: Open-Source

  -
    href: /blog
    label: 博客

  -
    href: /bookmark
    label: 书签

  -
    href: /about
    label: 关于

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-106555827-1'  # ex. UA-72165600-X

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Redis, Design Patterns]
skill_j2ee_keywords: [Spring, Spring-boot, Spring-cloud, Hibernate, MyBatis, JSP, Servlet]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, Vue, Boostrap]
